# Generated by Django 3.2.5 on 2021-07-28 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None),
        ),
    ]
