# Generated by Django 3.2.5 on 2021-07-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=120),
        ),
    ]
