# Generated by Django 3.2.5 on 2021-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20210729_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
