# Generated by Django 3.2.5 on 2021-08-07 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_show_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 12, 28, 717743, tzinfo=utc)),
        ),
    ]
