# Generated by Django 3.2.5 on 2021-08-02 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('image_link', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('website_link', models.URLField(blank=True, max_length=500, null=True)),
                ('seeking_talent', models.BooleanField(default=False)),
                ('seeking_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
