# Generated by Django 3.2.5 on 2021-08-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='seeking_talent',
            new_name='seeking_venue',
        ),
    ]
